### ISSUE TITLE
manque de fichier

### ISSUE THREAD

**Issue by simo97** [maxusr/agroaccess#1]
Yo max bjr, il manque le fichier app/bootstrap.php.cache et sa genère une erreur a la ligne 6 du fichier
**web/app.php**
Adonis

**Comment by maxusr** [comment]
Tu as fait composer install en ligne de commande?!

**Comment by maxusr** [comment]
<code>php composer install </vode>

**Comment by simo97** [comment]
ok j'ai fais sa mais j'ai pas la base de données , stp envoi sa

**Comment by maxusr** [comment]
La base de donnée s'installe en ligne de commande <code>php app/console doctrine:database:créateur</code> ensuite tu fais <code>php app/console doctrine:schema:update --force</code>

**Comment by simo97** [comment]
cool sa marche bien merci
